---
##test jwt
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1276530/public_html/api-dev/
    - /bin/rm -Rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R application/ $DEPLOYPATH
    - /bin/cp -R system/ $DEPLOYPATH
    - /bin/cp -R vendor/ $DEPLOYPATH
    - /bin/cp -R swagger/ $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH